server:
  http_listen_port: 0
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://354058:<token>@logs-prod-017.grafana.net/api/prom/push
        
scrape_configs:
- job_name: <staging|demo|master>-<id elocker>-elocker
  static_configs:
  - targets:
      - localhost
    labels:
      job: <staging|demo|master>-<id elocker>-elocker
      __path__: /var/log/*.log
- job_name: <staging|demo|master>-<id elocker>-mosquitto
  static_configs:
  - targets:
      - localhost
    labels:
      job: <staging|demo|master>-<id elocker>-mosquitto
      __path__: /var/log/mosquitto/*.log